import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import HomePage from '@/components/HomePage'
import ProductLists from '@/components/ProductLists'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'K-Buy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        <HomePage/>
        <ProductLists/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
